import Image from "next/image"
import { DownloadDropdown } from "@/components/download-dropdown"
import { getLatestRelease, getDownloadCount } from "@/lib/downloads"
import { SiteNav } from "@/components/site-nav"
import { SiteFooter } from "@/components/site-footer"
import { Reveal } from "@/components/reveal"
import { CopyCommand } from "@/components/copy-command"
import { Comparison } from "@/components/home/comparison"
import { FaqSection, faqs } from "@/components/home/faq"
import { SocialProof } from "@/components/social-proof"
import { CountUp } from "@/components/count-up"

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: { "@type": "Answer", text: faq.a },
  })),
}

function formatCount(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1).replace(/\.0$/, "")}K+`
  return String(n)
}

const features = [
  {
    label: "Capture",
    title: "Screenshots that need nothing else",
    body: "Region, fullscreen, and window capture with macOS's native selector. OCR text extraction, hex color picker, and a floating deck that holds up to five captures for copy, save, pin, edit, or drag-out.",
    tags: ["Region and fullscreen", "OCR", "Color picker", "Capture deck", "Capture on release"],
  },
  {
    label: "Record",
    title: "Cursor zoom that tracks you",
    body: "Pick a display, a window, or an area. The pointer is sampled at 30 Hz and clicks become smooth zoom moves, so a 4K screen stays readable in a small player. Recordings auto-save to your folder and survive a crash mid-take.",
    tags: ["Cursor auto-zoom", "Face cam", "Microphone", "Auto-save", "Pause and resume"],
  },
  {
    label: "Edit",
    title: "Two editors, one app",
    body: "Image editor: arrows, shapes, text, markers, highlight, blur, pixelate, and crop with background framing. Video editor: multi-clip timeline, speed control, transitions, captions, masks, and zoom cues.",
    tags: ["Image annotations", "Video timeline", "0.25x to 8x", "Backgrounds", "Color grading"],
  },
  {
    label: "Share",
    title: "Links you own, on your storage",
    body: "Connect a Cloudflare R2 bucket and Share uploads from the editor or the capture deck, then copies the link. No proxy, no vendor in the middle, no viewer limit.",
    tags: ["Your own R2 bucket", "Deck sharing", "Keychain keys", "Direct SigV4"],
  },
]

const performanceHighlights = [
  {
    stat: "Native",
    label: "macOS",
    body: "Built with Swift and AppKit. No Electron, no bundled browser, no web wrapper.",
  },
  {
    stat: "On-device",
    label: "transcription",
    body: "Captions generated by Apple's speech framework. Audio never touches a server.",
  },
  {
    stat: "30 Hz",
    label: "pointer tracking",
    body: "Cursor sampled 30 times per second for smooth, automatic zoom moves.",
  },
  {
    stat: "Crash-safe",
    label: "MP4",
    body: "Fragmented MP4 writes every frame as it arrives. Quit mid-recording, keep the file.",
  },
]

const moreFeatures = [
  { title: "75 customizable shortcuts", body: "Global captures, recording controls, deck actions, image tools, and video editing keys. Search, filter, and rebind with conflict detection." },
  { title: "URL scheme", body: "Trigger captures, recordings, OCR, or color picker from Raycast, Shortcuts, Alfred, or scripts with bettershot:// URLs." },
  { title: "Auto-save recordings", body: "Finished recordings save to your configured folder automatically. Manual Save on deck cards writes recordings too." },
  { title: "Backgrounds and beautify", body: "Padding, shadow, corner radius, and ten soft gradient backgrounds. Presentable screenshots and videos without a second app." },
  { title: "Cursor styling", body: "Recorded, Dark, Light, Dot, or native Hand cursor with adjustable size, motion smoothing, press effects, and idle hiding." },
  { title: "No watermark, no account", body: "Every export is clean. No trial, no upsell. BSD 3 Clause licensed and auditable." },
]

export default async function Home() {
  const [release, downloads] = await Promise.all([getLatestRelease(), getDownloadCount()])

  const stats = [
    { value: "$0", label: "Forever. No tiers, no trial" },
    { value: downloads > 0 ? formatCount(downloads) : "14K+", label: "Downloads and counting" },
    { value: "25 MB", label: "Lightweight native app" },
  ]

  return (
    <div className="min-h-screen bg-white text-zinc-900">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <SiteNav />

      <main id="main">
        <section className="pb-12 pt-28 sm:pt-36">
          <div className="mx-auto max-w-[1100px] px-6 text-center">
            <Reveal>
              <h1 className="mx-auto max-w-[18ch] text-[clamp(2.5rem,6vw,4.5rem)] font-normal leading-[1.1] tracking-tight text-zinc-900">
                One app for the whole screen.{" "}
                <span className="text-zinc-400">Free and open source.</span>
              </h1>
            </Reveal>

            <Reveal>
              <p className="mx-auto mt-6 max-w-lg text-[17px] leading-relaxed text-zinc-600">
                Screenshots, screen recording, image editor, and video editor, native on macOS.
                No subscription, no account, no telemetry. Nothing leaves your Mac unless you share it.
              </p>
            </Reveal>

            <Reveal>
              <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
                <DownloadDropdown release={release} source="hero" />
                <a
                  href="#features"
                  className="text-[15px] font-medium text-zinc-600 transition-colors hover:text-zinc-900"
                >
                  See what it does &rsaquo;
                </a>
              </div>
            </Reveal>

            <Reveal>
              <div className="mt-8 flex justify-center">
                <SocialProof />
              </div>
            </Reveal>

          </div>
        </section>

        <Reveal as="section" className="mx-auto max-w-[1100px] px-6 py-14" aria-label="Better Shot in numbers">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3 sm:gap-6">
            {stats.map((stat) => (
              <div key={stat.value} className="rounded-2xl border border-zinc-200 p-5 sm:p-6">
                <p className="text-[clamp(28px,3vw,42px)] font-semibold leading-[1.1] tracking-tight text-brand">
                  <CountUp value={stat.value} />
                </p>
                <p className="mt-2 text-[13px] leading-[18px] text-zinc-600">{stat.label}</p>
              </div>
            ))}
          </div>
        </Reveal>

        <section id="features" className="scroll-mt-20 py-20 sm:py-28">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-16 max-w-lg text-center">
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                One app instead of four subscriptions
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                Capture, record, annotate, edit, and share. All on your Mac, all in one app.
              </p>
            </Reveal>

            <div className="grid gap-6 md:grid-cols-2">
              {features.map((feature) => (
                <Reveal key={feature.label} className="rounded-2xl border border-zinc-200 p-6 sm:p-8">
                  <p className="mb-3 text-[13px] font-medium text-zinc-500">{feature.label}</p>
                  <h3 className="text-balance text-[26px] leading-tight sm:text-[28px]">
                    {feature.title}
                  </h3>
                  <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">{feature.body}</p>
                  <div className="mt-5 flex flex-wrap gap-1.5">
                    {feature.tags.map((tag) => (
                      <span key={tag} className="rounded-full bg-zinc-100 px-3 py-1 text-[12px] font-medium text-zinc-600">
                        {tag}
                      </span>
                    ))}
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        <section className="bg-zinc-50 py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-14 max-w-lg text-center">
              <p className="mb-3 text-[13px] font-medium uppercase tracking-widest text-zinc-400">
                Performance
              </p>
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                Built for macOS, not for Electron
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                Native from top to bottom. Light on CPU, light on battery, fast on every Mac.
              </p>
            </Reveal>

            <Reveal className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {performanceHighlights.map((item) => (
                <div key={item.stat} className="rounded-2xl border border-zinc-200 bg-white p-6">
                  <p className="text-[24px] tracking-tight text-brand">{item.stat}</p>
                  <p className="text-[13px] font-semibold uppercase tracking-widest text-zinc-400">{item.label}</p>
                  <p className="mt-3 text-[13px] leading-relaxed text-zinc-600">{item.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <section className="py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-12 max-w-lg text-center">
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                And everything else you need
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                From raw capture to the file you send, nothing missing.
              </p>
            </Reveal>

            <Reveal className="grid gap-px overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-200 sm:grid-cols-2 lg:grid-cols-3">
              {moreFeatures.map((f) => (
                <div key={f.title} className="bg-white p-6 transition-colors hover:bg-zinc-50">
                  <h3 className="text-[15px] font-semibold text-zinc-900">{f.title}</h3>
                  <p className="mt-2 text-[13px] leading-relaxed text-zinc-600">{f.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <section id="getting-started" className="scroll-mt-20 bg-zinc-50 py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <h2 className="text-balance text-[28px] sm:text-[32px]">Your first capture, in three steps</h2>
            <p className="mt-4 max-w-xl text-[16px] leading-relaxed text-zinc-600">
              Start with the menu bar. Set up the extras when you need them.
            </p>
            <ol className="mt-10 grid gap-8 md:grid-cols-3">
              {[
                { title: "Open BetterShot", body: "Install the app, then find the clover in your Mac’s menu bar. It’s your way back to captures, recent work, and Settings." },
                { title: "Choose what to capture", body: "Take a screenshot or open Recording options. Choose a display, window, or area. Include your camera or microphone only when you need them." },
                { title: "Make your point", body: "Open Edit from the preview. Add an arrow or a note to an image, or refine a recording. Export a file locally; cloud sharing is optional." },
              ].map((step, index) => (
                <li key={step.title}>
                  <span className="text-[14px] font-medium tabular-nums text-zinc-500">0{index + 1}</span>
                  <h3 className="mt-3 text-[18px] font-semibold">{step.title}</h3>
                  <p className="mt-2 text-[15px] leading-relaxed text-zinc-600">{step.body}</p>
                </li>
              ))}
            </ol>
            <p className="mt-10 max-w-2xl text-[14px] leading-relaxed text-zinc-600">
              New in 0.5.2: capture on mouse release, URL scheme for automation, auto-save
              recordings, and 75 customizable shortcuts. See the{" "}
              <a href="/changelog" className="text-brand-700 underline underline-offset-2 hover:text-brand">changelog</a>{" "}
              for the full list.
            </p>
          </div>
        </section>

        <Comparison />

        <FaqSection />

        <Reveal as="section" className="py-20 sm:py-28">
          <div className="mx-auto max-w-lg px-6 text-center">
            <Image
              src="/logo.png"
              alt="Better Shot"
              width={64}
              height={64}
              className="mx-auto mb-8 rounded-2xl shadow-lg shadow-brand/10"
            />
            <h2 className="text-[28px] tracking-tight sm:text-[32px]">
              Ready to try Better Shot?
            </h2>
            <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
              Free, open source, installed in about thirty seconds.
            </p>
            <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:gap-5 sm:justify-center">
              <DownloadDropdown release={release} source="cta" size="default" />
              <CopyCommand command="brew install --cask bettershot" />
            </div>
            <p className="mt-4 text-[13px] text-zinc-400">
              No account. No subscription. No uploads. macOS 26.0+.
            </p>
          </div>
        </Reveal>
      </main>

      <SiteFooter />
    </div>
  )
}
