import Link from "next/link"
import Image from "next/image"
import { ArrowUpRightIcon, GithubLogoIcon } from "@phosphor-icons/react/dist/ssr"
import { DownloadDropdown } from "@/components/download-dropdown"
import { getLatestRelease } from "@/lib/downloads"
import { SiteNav } from "@/components/site-nav"
import { SiteFooter } from "@/components/site-footer"
import { Reveal } from "@/components/reveal"
import { CopyCommand } from "@/components/copy-command"
import { Comparison } from "@/components/home/comparison"
import { FaqSection, faqs } from "@/components/home/faq"
import { StarCount } from "@/components/star-count"

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: { "@type": "Answer", text: faq.a },
  })),
}

const stats = [
  { value: "$0", label: "Forever. No tiers, no trial" },
  { value: "14K+", label: "Downloads and counting" },
  { value: "25 MB", label: "Lightweight native app" },
]

const features = [
  {
    label: "Record",
    title: "Cursor zoom that tracks you",
    body: "Pick a display, a window, or an area. The pointer is sampled at 30 Hz and clicks become smooth zoom moves, so a 4K screen stays readable in a small player. Recordings are written as fragmented MP4 and survive a crash mid-take.",
    tags: ["Cursor auto-zoom", "Face cam", "Microphone", "24/30/60 fps", "Pause and resume"],
  },
  {
    label: "Edit",
    title: "A timeline, not a trim slider",
    body: "Split at the playhead, drag an edge to trim, speed a slow stretch up to 4x, cross into the next clip. Then tilt the card, grade the color, set it on a background, and export MP4.",
    tags: ["Multi-clip timeline", "0.25x to 4x", "Transitions", "3D tilt", "Color grading"],
  },
  {
    label: "Overlay",
    title: "Captions and masks, on device",
    body: "Captions, keystrokes, masks, and text are timeline lanes you drag and retime next to your zoom cues. Transcription runs on device. A hide mask destroys its pixels in the export, so the password on screen never ships.",
    tags: ["Captions", "Keystrokes", "Blur and pixelate", "Spotlight", "Canvas text"],
  },
  {
    label: "Share",
    title: "Links you own, on your storage",
    body: "Connect a Cloudflare R2 bucket and Share uploads the edited recording straight from the app, then copies the link. No proxy, no vendor in the middle, no viewer limit.",
    tags: ["Your own R2 bucket", "Keychain keys", "Direct SigV4", "Edits baked in"],
  },
]

const performanceHighlights = [
  {
    stat: "Native",
    label: "macOS",
    body: "Built with Swift and AppKit. No Electron, no bundled browser, no web wrapper.",
  },
  {
    stat: "On-device",
    label: "transcription",
    body: "Captions generated by Apple's speech framework. Audio never touches a server.",
  },
  {
    stat: "30 Hz",
    label: "pointer tracking",
    body: "Cursor sampled 30 times per second for smooth, automatic zoom moves.",
  },
  {
    stat: "Crash-safe",
    label: "MP4",
    body: "Fragmented MP4 writes every frame as it arrives. Quit mid-recording, keep the file.",
  },
]

const moreFeatures = [
  { title: "Face cam bubble", body: "Record your face alongside your screen. Camera feed composited live during capture." },
  { title: "Microphone capture", body: "System audio and mic recorded on separate tracks. Mix or mute either one. Requires macOS 15." },
  { title: "Backgrounds and beautify", body: "Padding, shadow, corner radius, and gradient backgrounds. Presentable screenshots and videos without a second app." },
  { title: "Keyboard-first", body: "Six global shortcuts, all remappable. Capture, record, OCR, and color picker from anywhere." },
  { title: "OCR and color picker", body: "Extract text from any region. Sample any pixel on screen. Copy HEX, RGB, or HSL." },
  { title: "No watermark, no account", body: "Every export is clean. No trial, no upsell. BSD 3 Clause licensed and auditable." },
]

const featureVideos = [
  "/feature-1.mp4",
  "/feature-2.mp4",
  "/feature-3.mp4",
  "/feature-4.mp4",
]

export default async function Home() {
  const release = await getLatestRelease()

  return (
    <div className="min-h-screen bg-white text-zinc-900">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <SiteNav />

      <main id="main">
        <section className="pb-12 pt-28 sm:pt-36">
          <div className="mx-auto max-w-[1100px] px-6 text-center">
            <Reveal>
              <Link
                href="/changelog"
                className="inline-flex items-center gap-2 rounded-full border border-zinc-200 px-4 py-1.5 text-[13px] text-zinc-600 transition-colors hover:border-zinc-400"
              >
                <span className="font-semibold text-zinc-900">v{release.version}</span>
                <span className="h-3 w-px bg-zinc-200" />
                Auto-zoom, face cam, share links you own
                <ArrowUpRightIcon size={11} weight="bold" className="text-zinc-400" />
              </Link>
            </Reveal>

            <Reveal>
              <h1 className="mx-auto mt-10 max-w-[18ch] text-[clamp(2.5rem,6vw,4.5rem)] font-normal leading-[1.1] tracking-tight text-zinc-900">
                Screen recorder for Mac.{" "}
                <span className="text-zinc-400">Free and open source.</span>
              </h1>
            </Reveal>

            <Reveal>
              <p className="mx-auto mt-6 max-w-lg text-[17px] leading-relaxed text-zinc-600">
                A Mac screen recorder for clear, polished videos without complicated editing.
                Cursor auto-zoom, face cam, on-device captions, and share links you own.
              </p>
            </Reveal>

            <Reveal>
              <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
                <DownloadDropdown release={release} source="hero" />
                <a
                  href="#features"
                  className="text-[15px] font-medium text-zinc-600 transition-colors hover:text-zinc-900"
                >
                  See what it does &rsaquo;
                </a>
              </div>
            </Reveal>

            <Reveal>
              <p className="mt-6 flex items-center justify-center gap-2 text-[14px] text-zinc-600">
                <span className="text-amber-400">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
                <span>
                  Open source &middot; 25 MB &middot;{" "}
                  <a
                    href="https://github.com/KartikLabhshetwar/better-shot"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-brand transition-colors hover:text-brand-700"
                  >
                    <StarCount /> on GitHub
                  </a>
                </span>
              </p>
            </Reveal>

            <Reveal>
              <div className="mx-auto mt-12 max-w-[900px]">
                <div className="overflow-hidden rounded-2xl border border-zinc-200 shadow-xl shadow-zinc-200/50">
                  <video
                    autoPlay
                    loop
                    muted
                    playsInline
                    className="w-full"
                  >
                    <source src="/launch.mp4" type="video/mp4" />
                  </video>
                </div>
              </div>
            </Reveal>
          </div>
        </section>

        <Reveal as="section" className="mx-auto max-w-[1100px] px-6 py-14" aria-label="Better Shot in numbers">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3 sm:gap-6">
            {stats.map((stat) => (
              <div key={stat.value} className="rounded-2xl border border-zinc-200 p-5 sm:p-6">
                <p className="text-[clamp(28px,3vw,42px)] font-semibold leading-[1.1] tracking-tight text-brand">
                  {stat.value}
                </p>
                <p className="mt-2 text-[13px] leading-[18px] text-zinc-600">{stat.label}</p>
              </div>
            ))}
          </div>
        </Reveal>

        <section id="features" className="scroll-mt-20 py-20 sm:py-28">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-16 max-w-lg text-center">
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                One app instead of four subscriptions
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                Record, edit, caption, and share. Plus screenshots and annotations. All on your Mac.
              </p>
            </Reveal>

            {features.map((feature, i) => {
              const reversed = i % 2 === 1
              return (
                <Reveal
                  key={feature.label}
                  className={`grid items-center gap-12 lg:grid-cols-2 lg:gap-20${i > 0 ? " mt-20 sm:mt-32" : ""}`}
                >
                  <div className={reversed ? "order-1 lg:order-2" : ""}>
                    <p className="mb-3 text-[13px] font-medium uppercase tracking-widest text-zinc-400">
                      {feature.label}
                    </p>
                    <h3 className="text-[28px] leading-tight tracking-tight sm:text-[32px]">
                      {feature.title}
                    </h3>
                    <p className="mt-4 max-w-md text-[16px] leading-relaxed text-zinc-600">{feature.body}</p>
                    <div className="mt-5 flex flex-wrap gap-1.5">
                      {feature.tags.map((tag) => (
                        <span
                          key={tag}
                          className="rounded-full bg-zinc-100 px-3 py-1 text-[12px] font-medium text-zinc-600"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div className={reversed ? "order-2 lg:order-1" : ""}>
                    <div className="overflow-hidden rounded-2xl border border-zinc-200">
                      <video autoPlay loop muted playsInline className="w-full">
                        <source src={featureVideos[i]} type="video/mp4" />
                      </video>
                    </div>
                  </div>
                </Reveal>
              )
            })}
          </div>
        </section>

        <section className="bg-zinc-50 py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-14 max-w-lg text-center">
              <p className="mb-3 text-[13px] font-medium uppercase tracking-widest text-zinc-400">
                Performance
              </p>
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                Built for macOS, not for Electron
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                Native from top to bottom. Light on CPU, light on battery, fast on every Mac.
              </p>
            </Reveal>

            <Reveal className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {performanceHighlights.map((item) => (
                <div key={item.stat} className="rounded-2xl border border-zinc-200 bg-white p-6">
                  <p className="text-[24px] tracking-tight text-brand">{item.stat}</p>
                  <p className="text-[13px] font-semibold uppercase tracking-widest text-zinc-400">{item.label}</p>
                  <p className="mt-3 text-[13px] leading-relaxed text-zinc-600">{item.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <section className="py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-12 max-w-lg text-center">
              <h2 className="text-[28px] tracking-tight sm:text-[32px]">
                And everything else you need
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
                From raw capture to the file you send, nothing missing.
              </p>
            </Reveal>

            <Reveal className="grid gap-px overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-200 sm:grid-cols-2 lg:grid-cols-3">
              {moreFeatures.map((f) => (
                <div key={f.title} className="bg-white p-6 transition-colors hover:bg-zinc-50">
                  <h3 className="text-[15px] font-semibold text-zinc-900">{f.title}</h3>
                  <p className="mt-2 text-[13px] leading-relaxed text-zinc-600">{f.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <Comparison />

        <FaqSection />

        <Reveal as="section" className="py-20 sm:py-28">
          <div className="mx-auto max-w-lg px-6 text-center">
            <Image
              src="/logo.png"
              alt="Better Shot"
              width={64}
              height={64}
              className="mx-auto mb-8 rounded-2xl shadow-lg shadow-brand/10"
            />
            <h2 className="text-[28px] tracking-tight sm:text-[32px]">
              Ready to try Better Shot?
            </h2>
            <p className="mt-4 text-[16px] leading-relaxed text-zinc-600">
              Free, open source, installed in about thirty seconds.
            </p>
            <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:gap-5 sm:justify-center">
              <DownloadDropdown release={release} source="cta" size="default" />
              <CopyCommand command="brew install --cask bettershot" />
            </div>
            <p className="mt-4 text-[13px] text-zinc-400">
              No account. No subscription. No uploads. macOS 14+.
            </p>
          </div>
        </Reveal>
      </main>

      <SiteFooter />
    </div>
  )
}
