import Link from "next/link"
import Image from "next/image"
import { ArrowUpRightIcon, GithubLogoIcon } from "@phosphor-icons/react/dist/ssr"
import { DownloadDropdown } from "@/components/download-dropdown"
import { getLatestRelease } from "@/lib/downloads"
import { SiteNav } from "@/components/site-nav"
import { SiteFooter } from "@/components/site-footer"
import { Reveal } from "@/components/reveal"
import { CopyCommand } from "@/components/copy-command"
import { Comparison } from "@/components/home/comparison"
import { FaqSection, faqs } from "@/components/home/faq"

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.q,
    acceptedAnswer: { "@type": "Answer", text: faq.a },
  })),
}

const stats = [
  { value: "$0", label: "Forever. No tiers, no trial" },
  { value: "0 KB", label: "Uploaded by default" },
  { value: "30 Hz", label: "Pointer sampled while recording" },
  { value: "BSD 3", label: "Clause licensed, auditable" },
]

const features = [
  {
    label: "Record",
    title: "Cursor zoom that tracks you",
    body: "Pick a display, a window, or an area. The pointer is sampled at 30 Hz and clicks become smooth zoom moves, so a 4K screen stays readable in a small player. Recordings are written as fragmented MP4 and survive a crash mid-take.",
    tags: ["Cursor auto-zoom", "Face cam", "Microphone", "24/30/60 fps", "Pause and resume"],
  },
  {
    label: "Edit",
    title: "A timeline, not a trim slider",
    body: "Split at the playhead, drag an edge to trim, speed a slow stretch up to 4x, cross into the next clip. Then tilt the card, grade the color, set it on a background, and export MP4.",
    tags: ["Multi-clip timeline", "0.25x to 4x", "Transitions", "3D tilt", "Color grading"],
  },
  {
    label: "Overlay",
    title: "Captions and masks, on device",
    body: "Captions, keystrokes, masks, and text are timeline lanes you drag and retime next to your zoom cues. Transcription runs on device. A hide mask destroys its pixels in the export, so the password on screen never ships.",
    tags: ["Captions", "Keystrokes", "Blur and pixelate", "Spotlight", "Canvas text"],
  },
  {
    label: "Share",
    title: "Links you own, on your storage",
    body: "Connect a Cloudflare R2 bucket and Share uploads the edited recording straight from the app, then copies the link. No proxy, no vendor in the middle, no viewer limit.",
    tags: ["Your own R2 bucket", "Keychain keys", "Direct SigV4", "Edits baked in"],
  },
  {
    label: "Capture",
    title: "Screenshots, one shortcut away",
    body: "Region, window, or fullscreen from one shortcut. A floating preview appears after every shot, so you can edit it, copy it, pin it above your work, or drag the file straight into Figma, Slack, or Finder.",
    tags: ["Region", "Window", "Fullscreen", "OCR", "Color picker", "Pin on top"],
  },
  {
    label: "Annotate",
    title: "Arrows, shapes, text, badges",
    body: "Arrows, shapes, text, and numbered badges, each with its key printed in the corner of its button. Backgrounds, padding, shadow, and corner radius make the result presentable without a second app.",
    tags: ["Arrows", "Shapes", "Numbered badges", "Crop", "Backgrounds"],
  },
]

const performanceHighlights = [
  {
    stat: "Native",
    label: "macOS",
    body: "Built with Swift and AppKit. No Electron, no bundled browser, no web wrapper.",
  },
  {
    stat: "On-device",
    label: "transcription",
    body: "Captions generated by Apple's speech framework. Audio never touches a server.",
  },
  {
    stat: "30 Hz",
    label: "pointer tracking",
    body: "Cursor sampled 30 times per second for smooth, automatic zoom moves.",
  },
  {
    stat: "Crash-safe",
    label: "MP4",
    body: "Fragmented MP4 writes every frame as it arrives. Quit mid-recording, keep the file.",
  },
]

const moreFeatures = [
  { title: "Face cam bubble", body: "Record your face alongside your screen. Camera feed composited live during capture." },
  { title: "Microphone capture", body: "System audio and mic recorded on separate tracks. Mix or mute either one. Requires macOS 15." },
  { title: "Backgrounds and beautify", body: "Padding, shadow, corner radius, and gradient backgrounds. Presentable screenshots and videos without a second app." },
  { title: "Keyboard-first", body: "Six global shortcuts, all remappable. Capture, record, OCR, and color picker from anywhere." },
  { title: "OCR and color picker", body: "Extract text from any region. Sample any pixel on screen. Copy HEX, RGB, or HSL." },
  { title: "No watermark, no account", body: "Every export is clean. No trial, no upsell. BSD 3 Clause licensed and auditable." },
]

const placeholderGradients = [
  "from-violet-50 to-purple-50",
  "from-indigo-50 to-violet-50",
  "from-fuchsia-50 to-violet-50",
  "from-violet-50 to-blue-50",
  "from-purple-50 to-pink-50",
  "from-violet-50 to-indigo-50",
]

export default async function Home() {
  const release = await getLatestRelease()

  return (
    <div className="min-h-screen bg-white text-zinc-900">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <SiteNav />

      <main id="main">
        <section className="pb-10 pt-28 sm:pt-36">
          <div className="mx-auto max-w-[1100px] px-6 text-center">
            <Reveal>
              <Link
                href="/changelog"
                className="inline-flex items-center gap-2 rounded-full border border-zinc-200 px-4 py-1.5 text-[13px] text-zinc-500 transition-colors hover:border-zinc-400"
              >
                <span className="font-semibold text-zinc-900">v{release.version}</span>
                <span className="h-3 w-px bg-zinc-200" />
                Auto-zoom, face cam, share links you own
                <ArrowUpRightIcon size={11} weight="bold" className="text-zinc-400" />
              </Link>
            </Reveal>

            <Reveal>
              <h1 className="mx-auto mt-10 max-w-3xl text-[clamp(2.25rem,5.5vw,3.75rem)] font-extrabold leading-[1.08] tracking-tight">
                The free Loom alternative
                <br />
                <span className="text-brand">for macOS.</span>
              </h1>
            </Reveal>

            <Reveal>
              <p className="mx-auto mt-7 max-w-xl text-[17px] leading-relaxed text-zinc-500">
                Record your screen with cursor auto-zoom, edit on a real timeline with captions and
                masks, and share from your own R2 bucket. No subscription, no account, no
                five-minute cap. Free, open source, native macOS.
              </p>
            </Reveal>

            <Reveal>
              <div className="mt-10 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
                <DownloadDropdown release={release} source="hero" />
                <a
                  href="https://github.com/KartikLabhshetwar/better-shot"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 rounded-xl border border-zinc-200 px-6 py-3.5 text-[14px] font-semibold text-zinc-600 transition-all hover:border-zinc-300 hover:bg-zinc-50"
                >
                  <GithubLogoIcon size={16} weight="bold" />
                  View source
                </a>
              </div>
            </Reveal>

            <Reveal>
              <p className="mt-5 text-[13px] text-zinc-400">
                Free forever &middot; No account &middot; macOS 14+ &middot; Apple Silicon and Intel
              </p>
            </Reveal>
          </div>
        </section>

        <Reveal as="section" className="mx-auto max-w-[1100px] px-6 py-14" aria-label="Better Shot in numbers">
          <div className="grid grid-cols-2 gap-4 sm:gap-6 md:grid-cols-4">
            {stats.map((stat) => (
              <div key={stat.value} className="rounded-2xl border border-zinc-200 p-5 sm:p-6">
                <p className="text-[clamp(28px,3vw,42px)] font-extrabold leading-[1.1] tracking-tight text-brand">
                  {stat.value}
                </p>
                <p className="mt-2 text-[13px] leading-[18px] text-zinc-500">{stat.label}</p>
              </div>
            ))}
          </div>
        </Reveal>

        <section id="features" className="scroll-mt-20 py-20 sm:py-28">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-16 max-w-lg text-center">
              <h2 className="text-[28px] font-extrabold tracking-tight sm:text-[32px]">
                One app instead of four subscriptions
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-500">
                Record, edit, caption, and share. Plus screenshots and annotations. All on your Mac.
              </p>
            </Reveal>

            {features.map((feature, i) => {
              const reversed = i % 2 === 1
              return (
                <Reveal
                  key={feature.label}
                  className={`grid items-center gap-12 lg:grid-cols-2 lg:gap-20${i > 0 ? " mt-20 sm:mt-32" : ""}`}
                >
                  <div className={reversed ? "order-1 lg:order-2" : ""}>
                    <p className="mb-3 text-[13px] font-medium uppercase tracking-widest text-zinc-400">
                      {feature.label}
                    </p>
                    <h3 className="text-[28px] font-extrabold leading-tight tracking-tight sm:text-[32px]">
                      {feature.title}
                    </h3>
                    <p className="mt-4 max-w-md text-[16px] leading-relaxed text-zinc-500">{feature.body}</p>
                    <div className="mt-5 flex flex-wrap gap-1.5">
                      {feature.tags.map((tag) => (
                        <span
                          key={tag}
                          className="rounded-full bg-zinc-100 px-3 py-1 text-[12px] font-medium text-zinc-600"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div className={reversed ? "order-2 lg:order-1" : ""}>
                    <div className="overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-50">
                      <div className={`aspect-[4/3] bg-gradient-to-br ${placeholderGradients[i]}`} />
                    </div>
                  </div>
                </Reveal>
              )
            })}
          </div>
        </section>

        <section className="bg-zinc-50 py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-14 max-w-lg text-center">
              <p className="mb-3 text-[13px] font-medium uppercase tracking-widest text-zinc-400">
                Performance
              </p>
              <h2 className="text-[28px] font-extrabold tracking-tight sm:text-[32px]">
                Built for macOS, not for Electron
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-500">
                Native from top to bottom. Light on CPU, light on battery, fast on every Mac.
              </p>
            </Reveal>

            <Reveal className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {performanceHighlights.map((item) => (
                <div key={item.stat} className="rounded-2xl border border-zinc-200 bg-white p-6">
                  <p className="text-[24px] font-extrabold tracking-tight text-brand">{item.stat}</p>
                  <p className="text-[13px] font-semibold uppercase tracking-widest text-zinc-400">{item.label}</p>
                  <p className="mt-3 text-[13px] leading-relaxed text-zinc-500">{item.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <section className="py-16 sm:py-24">
          <div className="mx-auto max-w-[1100px] px-6">
            <Reveal className="mx-auto mb-12 max-w-lg text-center">
              <h2 className="text-[28px] font-extrabold tracking-tight sm:text-[32px]">
                And everything else you need
              </h2>
              <p className="mt-4 text-[16px] leading-relaxed text-zinc-500">
                From raw capture to the file you send, nothing missing.
              </p>
            </Reveal>

            <Reveal className="grid gap-px overflow-hidden rounded-2xl border border-zinc-200 bg-zinc-200 sm:grid-cols-2 lg:grid-cols-3">
              {moreFeatures.map((f) => (
                <div key={f.title} className="bg-white p-6 transition-colors hover:bg-zinc-50">
                  <h3 className="text-[15px] font-semibold text-zinc-900">{f.title}</h3>
                  <p className="mt-2 text-[13px] leading-relaxed text-zinc-500">{f.body}</p>
                </div>
              ))}
            </Reveal>
          </div>
        </section>

        <Comparison />

        <FaqSection />

        <Reveal as="section" className="py-20 sm:py-28">
          <div className="mx-auto max-w-lg px-6 text-center">
            <Image
              src="/logo.png"
              alt="Better Shot"
              width={64}
              height={64}
              className="mx-auto mb-8 rounded-2xl shadow-lg shadow-brand/10"
            />
            <h2 className="text-[28px] font-extrabold tracking-tight sm:text-[32px]">
              Ready to try Better Shot?
            </h2>
            <p className="mt-4 text-[16px] leading-relaxed text-zinc-500">
              Free, open source, installed in about thirty seconds.
            </p>
            <div className="mt-10 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
              <DownloadDropdown release={release} source="cta" />
              <CopyCommand command="brew install --cask bettershot" />
            </div>
            <p className="mt-4 text-[13px] text-zinc-400">
              No account. No subscription. No uploads. macOS 14+.
            </p>
          </div>
        </Reveal>
      </main>

      <SiteFooter />
    </div>
  )
}
